services:
  agent:
    name: "agent"
    display_name: "agent"
    description: "Token agent"
    host: 0.0.0.0
    port: 9977

  observer:
    name: "observer"
    display_name: "obserber"
    description: "Observer of agent service"
    host: 0.0.0.0
    port: 9977

installer:
  path_to_config: "/usr/local/etc/"
  path_to_bin: "/usr/local/bin/"

files:
  - metal_dealers.doc
  - late_hours.doc
  - skin_piercing.doc

address: 127.0.0.1
port: 8080
