services:
    agent:
        name: "12"
        display_name: d
        description: desc
        host: ""
        port: "0909"
    observer:
        name: obs
        display_name: serv
        description: descobs
        host: ""
        port: "8787"
installer:
    path_to_config: /usr/local/etc
    path_to_bin: /usr/local/bin
files:
    - agent
    - observer
address: localhost
port: "8080"
