.PHONY: clean
clean:
	rm -rf /usr/local/etc/aktiv.base
	rm /usr/local/bin/agent /usr/local/bin/observer
	rm /home/milchenko/programming/aktiv/installer/installer/tmp/observer /home/milchenko/programming/aktiv/installer/installer/tmp/agent
	rm /etc/systemd/system/Agent.service 
	rm /etc/systemd/system/Observer.service

